/**
 * Styles for the Pluck overlay, scoped inside a Shadow DOM so page CSS can't
 * touch them and they can't touch the page. Stored as a string and adopted by
 * the inspector's shadow root.
 */
(function (root) {
  'use strict';

  var css = [
    ':host {',
    '  all: initial;',
    '  --pluck-accent: #6366f1;',
    '  --pluck-accent-press: #4f46e5;',
    '  --pluck-accent-soft: rgba(99, 102, 241, 0.12);',
    '  --pluck-glass: rgba(20, 20, 30, 0.92);',
    '}',
    '',
    '.pluck-layer {',
    '  position: fixed;',
    '  inset: 0;',
    '  pointer-events: none;',
    '  z-index: 2147483647;',
    '  font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace;',
    '}',
    '',
    '/* the highlight box drawn over the targeted element */',
    '.pluck-box {',
    '  position: fixed;',
    '  pointer-events: none;',
    '  box-sizing: border-box;',
    '  border: 2px solid var(--pluck-accent);',
    '  border-radius: 6px;',
    '  background: var(--pluck-accent-soft);',
    '  box-shadow: 0 0 0 1px rgba(255, 255, 255, 0.6), 0 10px 30px rgba(49, 46, 129, 0.25);',
    '  opacity: 0;',
    '  transition: opacity 90ms ease;',
    '  will-change: top, left, width, height;',
    '}',
    '.pluck-box.is-on { opacity: 1; }',
    '',
    '/* floating label pill: tag.class#id · W×H */',
    '.pluck-label {',
    '  position: fixed;',
    '  pointer-events: none;',
    '  max-width: min(70vw, 560px);',
    '  padding: 5px 9px;',
    '  border-radius: 8px;',
    '  background: var(--pluck-glass);',
    '  color: #f4f4f5;',
    '  font-size: 12px;',
    '  line-height: 1.4;',
    '  letter-spacing: 0.1px;',
    '  white-space: nowrap;',
    '  overflow: hidden;',
    '  text-overflow: ellipsis;',
    '  backdrop-filter: blur(8px) saturate(140%);',
    '  -webkit-backdrop-filter: blur(8px) saturate(140%);',
    '  box-shadow: 0 6px 22px rgba(0, 0, 0, 0.32);',
    '  opacity: 0;',
    '  transform: translateY(2px);',
    '  transition: opacity 90ms ease, transform 90ms ease;',
    '}',
    '.pluck-label.is-on { opacity: 1; transform: translateY(0); }',
    '.pluck-label .pluck-tag { color: #a5b4fc; }',
    '.pluck-label .pluck-id { color: #fcd34d; }',
    '.pluck-label .pluck-cls { color: #f4f4f5; }',
    '.pluck-label .pluck-dim { color: #9ca3af; }',
    '',
    '/* confirmation toast */',
    '.pluck-toast {',
    '  position: fixed;',
    '  left: 50%;',
    '  bottom: 28px;',
    '  transform: translateX(-50%) translateY(8px);',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 9px;',
    '  max-width: min(80vw, 620px);',
    '  padding: 10px 14px;',
    '  border-radius: 12px;',
    '  background: rgba(20, 20, 30, 0.94);',
    '  color: #f4f4f5;',
    '  font-size: 13px;',
    '  line-height: 1.4;',
    '  backdrop-filter: blur(10px) saturate(140%);',
    '  -webkit-backdrop-filter: blur(10px) saturate(140%);',
    '  box-shadow: 0 12px 36px rgba(0, 0, 0, 0.42);',
    '  opacity: 0;',
    '  transition: opacity 180ms cubic-bezier(0.34, 1.56, 0.64, 1), transform 180ms cubic-bezier(0.34, 1.56, 0.64, 1);',
    '}',
    '.pluck-toast.is-on { opacity: 1; transform: translateX(-50%) translateY(0); }',
    '.pluck-toast .pluck-check {',
    '  flex: 0 0 auto;',
    '  width: 18px;',
    '  height: 18px;',
    '  border-radius: 50%;',
    '  background: var(--pluck-accent);',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '}',
    '.pluck-toast.is-error .pluck-check { background: #ef4444; }',
    '.pluck-toast.is-warn .pluck-check { background: #f59e0b; }',
    '.pluck-toast .pluck-check svg { width: 11px; height: 11px; display: block; }',
    '.pluck-toast .pluck-sel {',
    '  font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace;',
    '  font-size: 12px;',
    '  color: #c7d2fe;',
    '  white-space: nowrap;',
    '  overflow: hidden;',
    '  text-overflow: ellipsis;',
    '}',
    '',
    '/* dim hint chip top-center while inspecting */',
    '.pluck-hint {',
    '  position: fixed;',
    '  left: 50%;',
    '  top: 16px;',
    '  transform: translateX(-50%) translateY(-6px);',
    '  padding: 6px 12px;',
    '  border-radius: 999px;',
    '  background: rgba(79, 70, 229, 0.92);',
    '  color: #fff;',
    '  font-size: 12px;',
    '  font-weight: 500;',
    '  letter-spacing: 0.2px;',
    '  backdrop-filter: blur(8px) saturate(140%);',
    '  -webkit-backdrop-filter: blur(8px) saturate(140%);',
    '  box-shadow: 0 6px 18px rgba(49, 46, 129, 0.35);',
    '  opacity: 0;',
    '  transition: opacity 120ms ease, transform 120ms ease;',
    '}',
    '.pluck-hint.is-on { opacity: 1; transform: translateX(-50%) translateY(0); }',
    '.pluck-hint kbd {',
    '  font-family: inherit;',
    '  background: rgba(255, 255, 255, 0.22);',
    '  border-radius: 4px;',
    '  padding: 1px 5px;',
    '  margin: 0 1px;',
    '}',
    '',
    '@media (prefers-reduced-motion: reduce) {',
    '  .pluck-box, .pluck-label, .pluck-toast, .pluck-hint { transition: none; }',
    '}',
  ].join('\n');

  if (typeof window !== 'undefined') {
    window.__pluck = window.__pluck || {};
    window.__pluck.css = css;
  }
  if (typeof module !== 'undefined' && module.exports) module.exports = { css: css };
})(typeof self !== 'undefined' ? self : this);
